//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMA_WPF.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_DMAEntities : DbContext
    {
        public DB_DMAEntities()
            : base("name=DB_DMAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Appointment> Appointment { get; set; }
        public DbSet<Expedientes> Expedientes { get; set; }
        public DbSet<Gestion_Info> Gestion_Info { get; set; }
        public DbSet<Pacientes> Pacientes { get; set; }
        public DbSet<Pagos> Pagos { get; set; }
        public DbSet<Profile_Images> Profile_Images { get; set; }
        public DbSet<Stock_Images> Stock_Images { get; set; }
        public DbSet<Tratamiento> Tratamiento { get; set; }
    }
}
