//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMA_WPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacientes
    {
        public Pacientes()
        {
            this.Appointment = new HashSet<Appointment>();
            this.Expedientes = new HashSet<Expedientes>();
            this.Pagos = new HashSet<Pagos>();
            this.Profile_Images = new HashSet<Profile_Images>();
            this.Stock_Images = new HashSet<Stock_Images>();
            this.Tratamiento = new HashSet<Tratamiento>();
        }
    
        public int PacienteID { get; set; }
        public string Nombre { get; set; }
        public int Edad { get; set; }
        public System.DateTime Fecha_Nacimiento { get; set; }
        public string Sexo { get; set; }
        public string Estado_Civil { get; set; }
        public string Ocupacion { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string Direccion { get; set; }
        public string Nombre_Tutor { get; set; }
        public System.DateTime Alta { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<Appointment> Appointment { get; set; }
        public virtual ICollection<Expedientes> Expedientes { get; set; }
        public virtual ICollection<Pagos> Pagos { get; set; }
        public virtual ICollection<Profile_Images> Profile_Images { get; set; }
        public virtual ICollection<Stock_Images> Stock_Images { get; set; }
        public virtual ICollection<Tratamiento> Tratamiento { get; set; }
    }
}
